name: Update MAKE-PRS-HERE Branch

on:
  push:
    branches:
      - FrogPilot-Staging

  workflow_dispatch:

env:
  SOURCE_BRANCH: FrogPilot-Development
  TARGET_BRANCH: MAKE-PRS-HERE

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Checkout $TARGET_BRANCH branch
      run: |
        git checkout $TARGET_BRANCH

    - name: Apply changes from $SOURCE_BRANCH
      run: |
        git checkout $SOURCE_BRANCH
        git diff $TARGET_BRANCH > changes.diff
        git checkout $TARGET_BRANCH
        git apply changes.diff

    - name: Commit changes with the day's date
      run: |
        git add .

        day=$(TZ='America/Phoenix' date '+%-d')
        suffix="th"
        case $day in
          1|21|31) suffix="st" ;;
          2|22) suffix="nd" ;;
          3|23) suffix="rd" ;;
        esac
        commit_message="$(TZ='America/Phoenix' date '+%B ')$day$suffix, $(TZ='America/Phoenix' date '+%Y') Update"
        git commit -m "$commit_message" || echo "No changes to commit"

    - name: Push changes to $TARGET_BRANCH
      run: |
        git push origin $TARGET_BRANCH
